export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM

export const FULFILLED_ENTHUSIASM = 'FULFILLED_ENTHUSIASM'
export type FULFILLED_ENTHUSIASM = typeof FULFILLED_ENTHUSIASM

export const FETCH_RESOURCE = 'FETCH_RESOURCE'
export type FETCH_RESOURCE = typeof FETCH_RESOURCE

export const FETCH_RESOURCE_FULFILLED = 'FETCH_RESOURCE_FULFILLED'
export type FETCH_RESOURCE_FULFILLED = typeof FETCH_RESOURCE_FULFILLED
